services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    hostname: localhost
    ports:
      - "8929:8929"
      - "8922:22"
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 8922
        gitlab_rails['time_zone'] = 'Indian/Antananarivo'
        gitlab_rails['usage_ping_enabled'] = false
        gitlab_rails['gitlab_default_projects_features_container_registry'] = false
        puma['worker_processes'] = 0
        puma['threads_min'] = 1
        puma['threads_max'] = 2
        sidekiq['concurrency'] = 5
        prometheus_monitoring['enable'] = false
        postgresql['shared_buffers'] = '128MB'
        postgresql['max_worker_processes'] = 4
        nginx['worker_processes'] = 1
    shm_size: '256m'
    mem_limit: 4g
    restart: unless-stopped
    networks:
      - mlops_network

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    volumes:
      - gitlab_runner_config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    depends_on:
      - gitlab
    networks:
      - mlops_network

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
  gitlab_runner_config:

networks:
  mlops_network:
    name: mlops_network
    driver: bridge
